User.create!([
  {email: "didier.c62@numericable.fr", encrypted_password: "$2a$10$fMDsVIabxnbS4GnJZQIKH.OsnB1Pw0Vq668jQzYvX0s7cMn6nmU0G", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-03-11 00:15:26", last_sign_in_at: "2016-03-11 00:11:02", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"},
  {email: "toto@tutu.com", encrypted_password: "$2a$10$cdZDdHqjGSX6ylKiCtf2LO8uTyxoIBOLcuKAbR5OFxhE7jcMbGf7u", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-11 00:16:12", last_sign_in_at: "2016-03-11 00:16:12", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}
])
Element.create!([
  {fonction: "Entrepreneur Individuel", order: 0, date: "2011 à mars 2015", entite: "", description: "Entrepreneur Individuel en profession libéral.", tags: "", image_file_name: "3.png", image_content_type: "image/png", image_file_size: 12650, image_updated_at: "2016-03-13 11:55:44", resume: "", genre: "exp"},
  {fonction: "Administrateur Oracle Business Suite 11i", order: 1, date: "1999 à 2011", entite: "Capgemini Lille", description: "Administration d'instances Oracle et Oracle Applications v10.7 à v11i sous Oracle 7.3 à 11g en environnements développement et pre-production,\r\nAdministration système des serveurs Unix,\r\nInstallation et migration des instances,\r\nSauvegardes et restaurations,\r\nClonage des instances OA 11i,\r\nOptimisation des traitements par scripts,\r\ntuning", tags: "oracle, base de données, dba, unix, sauvegarde, restauration", image_file_name: "logo3.jpg", image_content_type: "image/jpeg", image_file_size: 4061, image_updated_at: "2016-03-13 12:03:15", resume: "DBA sur projets clients et interne", genre: "exp"},
  {fonction: "DBA Junior", order: 2, date: "mars à octobre 1999", entite: "Capgemini Lille", description: "Evolution vers Oracle 7.3.4 et la version 10.7 d’Oracle Applications Migration des spécifiques client,\r\nparamétrages et optimisation des traitements par scripts.", tags: "oracle, oracle applications, dba, ", image_file_name: "OA.png", image_content_type: "image/png", image_file_size: 6883, image_updated_at: "2016-03-13 12:15:14", resume: "Affecté au pôle migration de la BU Oracle de Capgemini en qualité DBA Junior.", genre: "exp"},
  {fonction: "Ingénieur de Développement", order: 3, date: "1998 à 1999", entite: "Capgemini Lille", description: "Modules GL, AP, AR, et AX d’Oracle Applications v10.7 ,\r\nContrôle de conformité et intégration en environnement type client,\r\nVérifications des pré-requis, paramétrage, tests d’intégration et de non-régression,\r\nElaboration de kits de livraisons (programmes d’installation par patchs automatisés en scripts shell et PL/SQL),\r\nUtilisation des outils de conduite de tests Win Runner et Test Director de MERCURY et QA RUN de COMPUWARE.", tags: "tests, intégration, oracle, oracle applications", image_file_name: "logo3.png", image_content_type: "image/png", image_file_size: 15029, image_updated_at: "2016-03-13 12:20:06", resume: "Validation de livrables spécifiques au sein de l'équipe intégration du projet finance international d’un grand compte régional", genre: "exp"},
  {fonction: "Maintenicien en instruments de bord", order: 4, date: "1989 à 1994", entite: "AERO-France (Paris- le Bourget) / Flandre Air (Lille)", description: "Maintenance, contrôle et dépannage des installations électriques, électroniques et de navigation,\r\nDépannage autonome hors base,\r\ngestion des moyens techniques et humains dans les dépannages à distance,\r\nHabilité à autoriser la remise en service avion après intervention.", tags: "aéronautique,", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, resume: "Assurer la disponibilité d’une flotte d’avions de ligne.", genre: "exp"},
  {fonction: "Etudiant métiers développement numérique", order: 0, date: "Octobre 2015 à Avril 2016", entite: "Simplon Roubaix", description: "Formation intensive aux métiers de développeur, travail en environnement linux, serveur vps dédié, https, nginx\r\n", tags: "Ruby, RoR, Ruby on rails, rails, html, html5, css, css3, javascript, bootstrap, foundation, git, github, atom, linux", image_file_name: "Logo-Simplon-Roubaix300.jpeg", image_content_type: "image/jpeg", image_file_size: 24345, image_updated_at: "2016-03-13 13:36:58", resume: "", genre: "form"},
  {fonction: "EUDIL / POLYTECH'LILLE", order: 1, date: "1998", entite: "EUDIL / POLYTECH'LILLE", description: "Diplôme  de l’Ecole Universitaire d’Ingénieur de Lille, EUDIL,\r\n             Option: Informatique.", tags: "POLYTECH'LILLE, ingénieur, EUDIL", image_file_name: "088.jpg", image_content_type: "image/jpeg", image_file_size: 2638, image_updated_at: "2016-03-13 13:40:54", resume: "EUDIL / POLYTECH'LILLE", genre: "form"},
  {fonction: "Formation d'administrateur base de données oracle", order: 2, date: "2001 à 2011", entite: "ORACLE University, Paris", description: "Formations d'administrateur base de données oracle 9i, 10g.,\r\n             Performance Tuning,\r\n             Oracle 9iAS", tags: "oracle, 9i, 10g, tuning, 9iAS", image_file_name: "oracle.jpg", image_content_type: "image/jpeg", image_file_size: 6000, image_updated_at: "2016-03-13 13:44:22", resume: "Formation d'administrateur base de données oracle", genre: "form"},
  {fonction: "Etudiant", order: 3, date: "1996", entite: "Université des sciences et technologies de Lille", description: "Licence d’Ingénierie électrique,\r\n Diplôme préparé en parallèle de la 1ère année de l’EUDIL", tags: "", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, resume: "Etudiant", genre: "form"}
])
Project.create!([
  {title: "CheatSheet VIM", description: "Création d'un cheatSheet sur l'éditeur de texte VI/VIM. Réalisé en pur css3/HTML5", language: "CSS3/HTML5", slug: "cheatsheet-vim", image_file_name: "088.jpg", image_content_type: "image/jpeg", image_file_size: 2638, image_updated_at: "2016-03-10 22:54:49", link: "http://didierclin.github.io/cheatSheet_vim/"},
  {title: "Goooogle", description: "Objet du projet:\r\n\r\nRéalisation d'une page google like en pur HTML/CSS", language: "CSS3/HTML5", slug: "goooogle", image_file_name: "gooogle.png", image_content_type: "image/png", image_file_size: 51106, image_updated_at: "2016-03-10 23:45:14", link: "http://didierclin.github.io/goooogle/"},
  {title: "Le canard", description: "Création d'un site intégrant une image cliquable. Le canard est inspiré du site Le Bon Coin (coin!)\r\n\r\nL'objectif est de mettre en place une carte avec des zones cliquables menant à des cibles distinctes.", language: "CSS3/HTML5", slug: "le-canard", image_file_name: "le_canard.png", image_content_type: "image/png", image_file_size: 73900, image_updated_at: "2016-03-10 23:56:07", link: "http://didierclin.github.io/leCanard"},
  {title: "Blog rails", description: "Site de blogging réalisé sous ruby on rails et déployé sur Heroku.\r\nGestion des utilisateurs", language: "Ruby_on_rails", slug: "blog-rails", image_file_name: "default.png", image_content_type: "image/png", image_file_size: 411815, image_updated_at: "2016-03-11 09:43:13", link: "https://proj03.herokuapp.com/"},
  {title: "Sample App Rails 4", description: "SIte from \"Ruby on Rails Tutorial (3rd Ed.) Learn Web Development with Rails\" from Michael Hartl. Le site se construit il est sous SSL ", language: "Ruby_on_rails", slug: "sample-app-rails-4", image_file_name: "logo-tuto.png", image_content_type: "image/png", image_file_size: 46942, image_updated_at: "2016-03-13 11:28:15", link: "https://sample-app-didier.herokuapp.com/"}
])
